name: test_arasim
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7


      - name: Install dependencies
        run: |
          
          sudo apt-get install dpkg-dev cmake g++ gcc binutils libx11-dev \
           libxpm-dev libxft-dev libxext-dev python libssl-dev libfftw3-dev libgsl-dev libboost-dev


      - name: Install ROOT
        run: |
          
          wget -q https://root.cern/download/root_v6.22.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
          tar -xzf root_v6.22.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
          source root/bin/thisroot.sh
          root --version


      - name: Install libRootFftwWrapper
        run: |
          
          source root/bin/thisroot.sh

          # download
          wget -q https://github.com/nichol77/libRootFftwWrapper/archive/master.tar.gz -O libRootFftwWrapper.tar.gz
          mkdir libRootFftwWrapper
          tar -xzf libRootFftwWrapper.tar.gz -C libRootFftwWrapper --strip-components=1
          rm libRootFftwWrapper.tar.gz
          

          # build
          cd libRootFftwWrapper
          make -j2
          sudo make install


      - name: Install AraRoot
        run: |

          # Download
          wget -q https://github.com/ara-software/AraRoot/archive/master.tar.gz -O araroot.tar.gz
          mkdir AraRoot
          tar -xzf araroot.tar.gz -C AraRoot --strip-contents=1
          rm araroot.tar.gz

          # build
          cd AraRoot
          export ARA_UTIL_INSTALL_DIR=`pwd`
          export ARA_ROOT_DIR=`pwd`
          bash INSTALL.sh 1
          cd ..

      - name: Build AraSim
        run: |

          source root/bin/thisroot.sh
          
          make -j2
          
      - name: Veff test
        run: |
          
          source root/bin/thisroot.sh
          export LD_LIBRARY_PATH="/home/runner/work/AraSim/AraSim/libRootFftwWrapper/build/:$LD_LIBRARY_PATH"

          bash test/veff_pa/run_veff_pa_test.sh





